### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by DcNiemandd** [bartosz11/playit-docker#1]
Hey,
when building there is error with wget permissions. And when I try to use container from docker hub, there is error with ./playit not being script/directory.
I tried to edit it, but it's my 1st time with docker, so... hope you'll find a way.
cheers

**Comment by bartosz11** [comment]
Hey, thanks for reporting this issue. I'll see what I can do tomorrow.

**Comment by bartosz11** [comment]
@DcNiemandd I think I managed to fix the issue with build. Can you try cloning this repo again and rebuilding the image?
If something is still wrong, please provide a screenshot of error here.

**Comment by slaygirlz** [comment]
this issue is sill happening

**Comment by slaygirlz** [comment]
still
